Set up CI with Azure Pipelines
[skip ci]

diff --git a/front/azure-pipelines.yml b/front/azure-pipelines.yml
--- a/front/azure-pipelines.yml
+++ b/front/azure-pipelines.yml
@@ -8,12 +8,10 @@ trigger:
     exclude:
       - back/*
 
-variables:
-  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
-  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)' 
 
+variables:
   # Container registry service connection established during pipeline creation
-  dockerfilePath: 'front/Dockerfile'
+  dockerfilePath: 'back/Dockerfile'
   buildTag: '$(Build.BuildId)'
   latestTag: 'latest'
   
@@ -25,43 +23,43 @@ stages:
     jobs:
     - job: 'build'
       steps:
-        - task: NodeTool@0
-          inputs:
-            versionSpec: "10.x"
-          displayName: "Install Node.js"
+      - task: NodeTool@0
+        inputs:
+          versionSpec: "10.x"
+        displayName: "Install Node.js"
 
-        - script: npm install
-          displayName: "Install NPM"
-          
-        - script: npm run dev
-          displayName: "Build"
+      - script: npm install
+        displayName: "Install NPM"
+
+      - script: npm run dev          
+        displayName: Build App
+
 
   - stage: 'Test'
     displayName: 'Test React App'
     jobs:
     - job: 'test'
       steps:
-        - script: |
-            curl -X GET http://localhost:3000 > response.txt
-            if grep -q "E-commerce" response.txt; then
-              echo "Data found in the response"
-            else
-              echo "Data not found in the response"
-              exit 1
-            fi
-          failOnStderr: true
-          workingDirectory: $(Build.SourcesDirectory)
-          condition: and(succeeded()
-          continueOnError: false
-          target: host
-          enabled: true
-          env:
-            TEST_ENVIRONMENT: staging
-            TEST_SUITE: full
-          name: "RunTests"
-          retryCountOnTaskFailure: 1
-          displayName: Validate with curl
-
+      - script:  |
+          response=$(curl -X GET -s -o /dev/null -w "%{http_code}" https://localhost:8080)
+          if [[ "$response" -eq 200 ]]; then
+            echo "Request was successful"
+          else
+            echo "Request failed with status code $response"
+            exit 1
+          fi
+        failOnStderr: true
+        workingDirectory: $(Build.SourcesDirectory)\
+        condition: and(succeeded()
+        continueOnError: false
+        target: host
+        enabled: true
+        env:
+          TEST_ENVIRONMENT: staging
+          TEST_SUITE: full
+        name: "RunTests"
+        retryCountOnTaskFailure: 1
+        displayName: Test App
 
   - stage: 'Release_Docker_Hub'
     displayName: 'Release into DockerHub'
