Update azure-pipelines.yml for Azure Pipelines

diff --git a/front/azure-pipelines.yml b/front/azure-pipelines.yml
--- a/front/azure-pipelines.yml
+++ b/front/azure-pipelines.yml
@@ -55,8 +55,13 @@ stages:
 
       - script:  |
           npm run dev &
-          sleep 15
-          curl localhost:3000
+          response=$(curl -X GET -s -o /dev/null -w "%{http_code}" http://localhost:3000)
+          if [[ "$response" -eq 200 ]]; then
+            echo "Request was successful"
+          else
+            echo "Request failed with status code $response"
+            exit 1
+          fi
         workingDirectory: $(Build.SourcesDirectory)/front/
         timeoutInMinutes: 1
         retryCountOnTaskFailure: 0
